---
title: "AsthmaCEA_Figures&Tables"
author: "Joseph"
date: "2022-10-14"
output: 
  html_document: 
    toc: yes
    theme: journal
editor_options: 
  chunk_output_type: console
---

# SETUP

```{r,  Library, include=F}
library(here)
library(tidyverse)
library(dplyr)
library(readxl)
library(dampack)
library(ggplot2)
library(kableExtra)
library(purrr)

```

```{r, f_gen_base input, include=FALSE}
f_gen_base <- function(n_sim = 1){
  
  require(truncnorm)  
  
### Asthma Control Probability ### (proportion: mean % of weeks with well controlled asthma)l
  p.H0_AC <- p.PRIM_AC <-  0.311
  p.SYM_AC <- 0.344
  p.H1_AC <- 0.444
  
### OTHER ### 
  #H0 entering H1
  p.H0_H1 <- 0
  
  #H1 Adherence
  pAnn.H1_H0  <- (1-0.79)                             # probability of non-adherence to HCP management
  p.H1_H0  <- 1 - (1-pAnn.H1_H0)^(1/52)

  #SEVR -> H1 (Recovery) - mean of 4 weeks
  wk.SEVR_H1 <- 4
  r.SEVR_H1 <- 1/wk.SEVR_H1                   #weekly rate of 1 event (event being leaving SEVR state)
  p.SEVR_H1 <- 1-exp(-r.SEVR_H1)
  
### SEV (Severe Exacerbation) ###
  p.SCS_H0 <- p.ED_H0 <-p.Hosp_H0 <- 0 #Assumption that following severe exacerbation patient enters H1
  RR.NC <- 1.201 #RATE ratio of exacerbation for not controlled asthma
  
  #Exacerbation proportion (SCS, ED, HOSP)
  prop.H0_SEV <- prop.PRIM_SEV <- c(0.776,0.130,0.094)
  prop.SYM_SEV <- c(0.819,0.102,0.079)
  prop.H1_SEV <- c(0.824,0.098,0.078)
  
  #Cumulative rate from SYGMA trials
  r.H0_SEVtot <- 0.20 #syg1
  r.SYM_SEVtot <- 0.11 #syg2
  r.H1_SEVtot <- 0.09 #syg1
  
    #Rate of exacerbation by control group
    #controlled (C)
    r.H0C_SEV <- r.H0_SEVtot/(p.H0_AC + RR.NC - RR.NC*p.H0_AC) #yaghoubi et al.2020
    r.SYMC_SEV <- r.SYM_SEVtot/(p.SYM_AC + RR.NC - RR.NC*p.SYM_AC) #yaghoubi et al.2020
    r.H1C_SEV <- r.H1_SEVtot/(p.H1_AC + RR.NC - RR.NC*p.H1_AC) #yaghoubi et al.2020
    
    #Not controlled (NC)
    r.H0NC_SEV <- r.H0C_SEV * RR.NC
    r.SYMNC_SEV <- r.SYMC_SEV * RR.NC
    r.H1NC_SEV <- r.H1C_SEV * RR.NC

 ## Transition probabilities for Severe exacerbation #
      #Severe Exacerbation Rates * Exacerbation Proportion
  
      #controlled (C)
        p.H0C_SCS <- (1-exp(-r.H0C_SEV/52)) * prop.H0_SEV[1] # weekly probability of severe exacerbation with no OTC or primatene OTC prn
        p.H0C_ED <- (1-exp(-r.H0C_SEV/52)) * prop.H0_SEV[2]
        p.H0C_Hosp <- (1-exp(-r.H0C_SEV/52)) * prop.H0_SEV[3]
        
        p.SYMC_SCS <- (1-exp(-r.SYMC_SEV/52)) * prop.SYM_SEV[1]	# weekly rate of severe exacerbation with symbicort PRN
        p.SYMC_ED <- (1-exp(-r.SYMC_SEV/52)) * prop.SYM_SEV[2]
        p.SYMC_Hosp <- (1-exp(-r.SYMC_SEV/52)) * prop.SYM_SEV[3]
        
        p.H1C_SCS <- (1-exp(-r.H1C_SEV/52)) * prop.H1_SEV[1]	# weekly rate of severe exacerbation with HCP management (low dose ICS + SABA)
        p.H1C_ED <- (1-exp(-r.H1C_SEV/52)) * prop.H1_SEV[2]
        p.H1C_Hosp <- (1-exp(-r.H1C_SEV/52)) * prop.H1_SEV[3]
      
      #Not controlled (NC)
        p.H0NC_SCS <- (1-exp(-r.H0NC_SEV/52)) * prop.H0_SEV[1] # weekly probability of severe exacerbation with no OTC or primatene OTC prn
        p.H0NC_ED <- (1-exp(-r.H0NC_SEV/52)) * prop.H0_SEV[2]
        p.H0NC_Hosp <- (1-exp(-r.H0NC_SEV/52)) * prop.H0_SEV[3]
        
        p.SYMNC_SCS <- (1-exp(-r.SYMNC_SEV/52)) * prop.SYM_SEV[1]	# weekly rate of severe exacerbation with symbicort PRN
        p.SYMNC_ED <- (1-exp(-r.SYMNC_SEV/52)) * prop.SYM_SEV[2]
        p.SYMNC_Hosp <- (1-exp(-r.SYMNC_SEV/52)) * prop.SYM_SEV[3]
        
        p.H1NC_SCS <- (1-exp(-r.H1NC_SEV/52)) * prop.H1_SEV[1]	# weekly rate of severe exacerbation with HCP management (low dose ICS + SABA)
        p.H1NC_ED <- (1-exp(-r.H1NC_SEV/52)) * prop.H1_SEV[2]
        p.H1NC_Hosp <- (1-exp(-r.H1NC_SEV/52)) * prop.H1_SEV[3]
        
### Mortality parameters built in markov model ###
        
### Cost and utility inputs ###
  ## Direct Medical costs (per week)
  c.HCP     <- 53               # cost of HCP management
  c.AU      <- 15              # cost of uncontrolled asthma week
  c.SCS     <- 163               # cost of being in SCS 
  c.ED      <- 744               # cost of being in ED
  c.Hosp    <- 12398               # cost of being in HOSP
  
  ## Drug acquisition cost (per DAY) * 7 
  c.PRIM     <- 29.78*(0.52/160) * 7               # cost of primatene
  c.SYM      <- 311.49*(0.52/120) * 7            # cost of symbicort
  c.ICS      <- 326.28*(2/120) * 7               # cost of ICS
  c.SABA     <- 54.42*(0.49/200) * 7             # cost of SABA
  c.ICS_SABA <- c.ICS + c.SABA
  
  ## Indirect costs 
  c.timeHCP  <- 3.03 # HCP management time/week*Assuming 240 total minutes of 4 PCP visits per year, 20 min travel time, 40min wait, median wage $1037 in 2022
  c.prodAU   <- 132  # cost of productivity loss due to asthma not controlled days per week*
  
  #Productivity loss due to severe exacerbation ** Assuming do not go to work for 2,4,7 days
  c.prodSCS  <- 296 # productive lose due to severe exacerbation.
  c.prodED <- 593
  c.prodHosp <- 1037
  
  ## Utility
  du.AU   <-  -0.07/52                # disutility of asthma uncontrolled week
  du.SCS  <-  -0.10/52               # disutility of systemic corticosteroid use
  du.ED   <-  -0.15/52                 # disutility of emergency department
  du.Hosp <-  -0.20/52                 # disutility of hospitalization
  
  u.H0 <- 0.87/52          # utility of non-exacerbation
  u.H1 <- u.H0
  u.SCS <- u.H0 + du.SCS     # utility of SCS
  u.ED  <- u.H0 + du.ED        # utility of emergency deparment 
  u.Hosp<- u.H0 + du.Hosp   # utility of hospitalization

################################################################################################################################
### Parameter dataframe ###
df_psa <- data.frame(
    ## Asthma Control Probability (proportion: mean % of weeks with well controlled asthma)l
      p.H0_AC,
      p.PRIM_AC,
      p.SYM_AC,
      p.H1_AC,
      
    ## Transition probabilities #
      #controlled (C)
      p.H0C_SCS,
      p.H0C_ED,
      p.H0C_Hosp,
      
      p.SYMC_SCS,
      p.SYMC_ED,
      p.SYMC_Hosp,
      
      p.H1C_SCS,
      p.H1C_ED,
      p.H1C_Hosp,
      
      #Not controlled (NC)
      p.H0NC_SCS,
      p.H0NC_ED,
      p.H0NC_Hosp,
      
      p.SYMNC_SCS,
      p.SYMNC_ED,
      p.SYMNC_Hosp,
      
      p.H1NC_SCS,
      p.H1NC_ED,
      p.H1NC_Hosp,
    
      #SEVR -> H1
      p.SEVR_H1, #Weekly probability of exiting SEVR
    
      #H0
      p.H0_H1,
    
      #H1
      p.H1_H0,
    
    ### Cost and utility inputs ###
      ## Direct Medical costs (per week)
      c.HCP, 
      c.AU,
      c.SCS,
      c.ED,
      c.Hosp,
      
      ## Drug acquisition cost (per DAY) * 7 
      c.PRIM,
      c.SYM,
      c.ICS,
      c.SABA,
      c.ICS_SABA,
      
      ## Indirect costs 
      c.timeHCP,
      c.prodAU,
      
      #Productivity loss due to severe exacerbation ** Assuming do not go to work for 2,4,7 days
      c.prodSCS,
      c.prodED,
      c.prodHosp,
      
      ## Utility
      du.AU,
      du.SCS,
      du.ED,
      du.Hosp,
      
      u.H0,
      u.H1,
      u.SCS,
      u.ED,
      u.Hosp
      
  )
  
  v.du_exac  <- c(du.SCS, du.ED, du.Hosp)
  v.u_exac  <- c(u.SCS, u.ED, u.Hosp)
  return(df_psa)

}
```

```{r, f_gen_dsa input, include=F}
f_gen_dsa <- function(n_sim = 2,
                      DSA = FALSE){
  
  require(truncnorm)  

  r <- c(0.8,1.2)
### Asthma Control Probability ### (proportion: mean % of weeks with well controlled asthma)l
  p.H0_AC <- p.PRIM_AC <-  0.311
  p.SYM_AC <- 0.344
  p.H1_AC <- 0.444
  
### OTHER ###  
  #H0 entering H1
  pAnn.H0_H1 <- 0
  if(DSA=="H0_H1"){pAnn.H0_H1 <- c(0,0.2)}
  p.H0_H1  <- 1 - (1-pAnn.H0_H1)^(1/52)
  
  #H1 Adherence
  pAnn.H1_H0  <- (1-0.79)                             # probability of non-adherence to HCP management
  if(DSA=="H1_H0"){pAnn.H1_H0 <- 0.21 * r}
  p.H1_H0  <- 1 - (1-pAnn.H1_H0)^(1/52)

  #SEVR -> H1 (Recovery) - mean of 4 weeks
  wk.SEVR_H1 <- 4
  r.SEVR_H1 <- 1/wk.SEVR_H1                   #weekly rate of 1 event (event being leaving SEVR state)
  p.SEVR_H1 <- 1-exp(-r.SEVR_H1)
  
### SEV (Severe Exacerbation) ###
  p.SCS_H0 <- p.ED_H0 <-p.Hosp_H0 <- 0 #Assumption that following severe exacerbation patient enters H1
  RR.NC <- 1.201 #RATE ratio of exacerbation for not controlled asthma
  
  #Exacerbation proportion (SCS, ED, HOSP)
  prop.H0_SEV <- prop.PRIM_SEV <- c(0.776,0.130,0.094)
  prop.SYM_SEV <- c(0.819,0.102,0.079)
  prop.H1_SEV <- c(0.824,0.098,0.078)
  
  #Cumulative rate from SYGMA trials
  r.H0_SEVtot <- 0.20 #syg1
  if(DSA=="r.H0"){r.H0_SEVtot <- 0.20*r}
  
  r.SYM_SEVtot <- 0.11 #syg2
  if(DSA=="r.SYM"){r.SYM_SEVtot <- 0.11*r}

  r.H1_SEVtot <- 0.09 #syg1
  if(DSA=="r.H1"){r.H1_SEVtot <- 0.09*r}

    #Rate of exacerbation by control group
    #controlled (C)
    r.H0C_SEV <- r.H0_SEVtot/(p.H0_AC + RR.NC - RR.NC*p.H0_AC) #yaghoubi et al.2020
    r.SYMC_SEV <- r.SYM_SEVtot/(p.SYM_AC + RR.NC - RR.NC*p.SYM_AC) #yaghoubi et al.2020
    r.H1C_SEV <- r.H1_SEVtot/(p.H1_AC + RR.NC - RR.NC*p.H1_AC) #yaghoubi et al.2020
    
    #Not controlled (NC)
    r.H0NC_SEV <- r.H0C_SEV * RR.NC
    r.SYMNC_SEV <- r.SYMC_SEV * RR.NC
    r.H1NC_SEV <- r.H1C_SEV * RR.NC

 ## Transition probabilities for Severe exacerbation #
      #Severe Exacerbation Rates * Exacerbation Proportion
  
      #controlled (C)
        p.H0C_SCS <- (1-exp(-r.H0C_SEV/52)) * prop.H0_SEV[1] # weekly probability of severe exacerbation with no OTC or primatene OTC prn
        p.H0C_ED <- (1-exp(-r.H0C_SEV/52)) * prop.H0_SEV[2]
        p.H0C_Hosp <- (1-exp(-r.H0C_SEV/52)) * prop.H0_SEV[3]
        
        p.SYMC_SCS <- (1-exp(-r.SYMC_SEV/52)) * prop.SYM_SEV[1]	# weekly rate of severe exacerbation with symbicort PRN
        p.SYMC_ED <- (1-exp(-r.SYMC_SEV/52)) * prop.SYM_SEV[2]
        p.SYMC_Hosp <- (1-exp(-r.SYMC_SEV/52)) * prop.SYM_SEV[3]
        
        p.H1C_SCS <- (1-exp(-r.H1C_SEV/52)) * prop.H1_SEV[1]	# weekly rate of severe exacerbation with HCP management (low dose ICS + SABA)
        p.H1C_ED <- (1-exp(-r.H1C_SEV/52)) * prop.H1_SEV[2]
        p.H1C_Hosp <- (1-exp(-r.H1C_SEV/52)) * prop.H1_SEV[3]
      
      #Not controlled (NC)
        p.H0NC_SCS <- (1-exp(-r.H0NC_SEV/52)) * prop.H0_SEV[1] # weekly probability of severe exacerbation with no OTC or primatene OTC prn
        p.H0NC_ED <- (1-exp(-r.H0NC_SEV/52)) * prop.H0_SEV[2]
        p.H0NC_Hosp <- (1-exp(-r.H0NC_SEV/52)) * prop.H0_SEV[3]
        
        p.SYMNC_SCS <- (1-exp(-r.SYMNC_SEV/52)) * prop.SYM_SEV[1]	# weekly rate of severe exacerbation with symbicort PRN
        p.SYMNC_ED <- (1-exp(-r.SYMNC_SEV/52)) * prop.SYM_SEV[2]
        p.SYMNC_Hosp <- (1-exp(-r.SYMNC_SEV/52)) * prop.SYM_SEV[3]
        
        p.H1NC_SCS <- (1-exp(-r.H1NC_SEV/52)) * prop.H1_SEV[1]	# weekly rate of severe exacerbation with HCP management (low dose ICS + SABA)
        p.H1NC_ED <- (1-exp(-r.H1NC_SEV/52)) * prop.H1_SEV[2]
        p.H1NC_Hosp <- (1-exp(-r.H1NC_SEV/52)) * prop.H1_SEV[3]
        
### Mortality parameters built in markov model ###
        
### Cost and utility inputs ###
  ## Direct Medical costs (per week)
  c.HCP     <- 53               # cost of HCP management
  if(DSA=="HCP"){c.HCP <- 53*r}
  
  c.AU      <- 15              # cost of uncontrolled asthma week
  if(DSA=="AU"){c.AU <- 15*r}
  
  c.SCS     <- 163               # cost of being in SCS 
  if(DSA=="SCS"){c.SCS <- 163*r}
  
  c.ED      <- 744               # cost of being in ED
  if(DSA=="ED"){c.ED <- 744*r}
  
  c.Hosp    <- 12398               # cost of being in HOSP
  if(DSA=="Hosp"){c.Hosp <- 12398*r}
  
  ## Drug acquisition cost (per DAY) * 7 
  #Med inhalations & Drug Acquisition
    inh.PRIM <- 0.52
    if(DSA=="inh.PRIM"){inh.PRIM <- 0.52*r}
    
    inh.SYM <- 0.52
    if(DSA=="inh.SYM"){inh.SYM <- 0.52*r}
    
    inh.ICS <- 2
    if(DSA=="inh.ICS"){inh.ICS <- 2*r}
    
    inh.SABA <- 0.49
    if(DSA=="inh.SABA"){inh.SABA <- 0.49*r}

  
    c.PRIM     <- 29.78*(inh.PRIM/160) * 7               # cost of primatene
    c.SYM      <- 311.49*(inh.SYM/120) * 7            # cost of symbicort
    c.ICS      <- 326.28*(inh.ICS/120)* 7               # cost of ICS
    c.SABA     <- 54.42*(inh.SABA/200)* 7             # cost of SABA
    c.ICS_SABA <- c.ICS + c.SABA

  
  ## Indirect costs 
  c.timeHCP  <- 3.03 # HCP management time/week*Assuming 240 total minutes of 4 PCP visits per year, 20 min travel time, 40min wait, median wage $1037 in 2022
  c.prodAU   <- 132  # cost of productivity loss due to asthma not controlled days per week*
  
  #Productivity loss due to severe exacerbation ** Assuming do not go to work for 2,4,7 days
  c.prodSCS  <- 296 # productive lose due to severe exacerbation.
  c.prodED <- 593
  c.prodHosp <- 1037

  
  ## Utility
  du.AU   <-  -0.07/52                # disutility of asthma uncontrolled week
  if(DSA=="du.AU"){du.AU <- (-0.07/52) * r}
  
  du.SCS  <-  -0.10/52               # disutility of systemic corticosteroid use
  if(DSA=="du.SCS"){du.SCS <- (-0.10/52) * r}

  du.ED   <-  -0.15/52                 # disutility of emergency department
  if(DSA=="du.ED"){du.ED <- (-0.15/52) * r}

  du.Hosp <-  -0.20/52                 # disutility of hospitalization
  if(DSA=="du.Hosp"){du.Hosp <- (-0.20/52) * r}

  
  u.H0 <- 0.87/52          # utility of non-exacerbation
  if(DSA=="u.H0"){u.H0 <- c(0.87/52*0.8, 1)}
  u.H1 <- u.H0
  u.SCS <- u.H0 + du.SCS     # utility of SCS
  u.ED  <- u.H0 + du.ED        # utility of emergency deparment 
  u.Hosp<- u.H0 + du.Hosp   # utility of hospitalization

################################################################################################################################
### Parameter dataframe ###
df_psa <- data.frame(
    ## Asthma Control Probability (proportion: mean % of weeks with well controlled asthma)l
      p.H0_AC,
      p.PRIM_AC,
      p.SYM_AC,
      p.H1_AC,
      
    ## Transition probabilities #
      #controlled (C)
      p.H0C_SCS,
      p.H0C_ED,
      p.H0C_Hosp,
      
      p.SYMC_SCS,
      p.SYMC_ED,
      p.SYMC_Hosp,
      
      p.H1C_SCS,
      p.H1C_ED,
      p.H1C_Hosp,
      
      #Not controlled (NC)
      p.H0NC_SCS,
      p.H0NC_ED,
      p.H0NC_Hosp,
      
      p.SYMNC_SCS,
      p.SYMNC_ED,
      p.SYMNC_Hosp,
      
      p.H1NC_SCS,
      p.H1NC_ED,
      p.H1NC_Hosp,
    
      #SEVR -> H1
      p.SEVR_H1, #Weekly probability of exiting SEVR
    
      #H0
      p.H0_H1,
    
      #H1
      p.H1_H0,
    
    ### Cost and utility inputs ###
      ## Direct Medical costs (per week)
      c.HCP, 
      c.AU,
      c.SCS,
      c.ED,
      c.Hosp,
      
      ## Drug acquisition cost (per DAY) * 7 
      c.PRIM,
      c.SYM,
      c.ICS,
      c.SABA,
      c.ICS_SABA,
      
      ## Indirect costs 
      c.timeHCP,
      c.prodAU,
      
      #Productivity loss due to severe exacerbation ** Assuming do not go to work for 2,4,7 days
      c.prodSCS,
      c.prodED,
      c.prodHosp,
      
      ## Utility
      du.AU,
      du.SCS,
      du.ED,
      du.Hosp,
      
      u.H0,
      u.H1,
      u.SCS,
      u.ED,
      u.Hosp
      
  )
  
  v.du_exac  <- c(du.SCS, du.ED, du.Hosp)
  v.u_exac  <- c(u.SCS, u.ED, u.Hosp)
  return(df_psa)

}

dsa_params<-c("H0_H1","H1_H0",
               "r.H0","r.SYM", "r.H1",
               "HCP","AU","SCS","ED","Hosp",
               "inh.PRIM","inh.SYM","inh.ICS","inh.SABA",
               "du.AU","du.SCS","du.ED","du.Hosp","u.H0")


```

```{r, f_gen_psa input, include =F}
psa_param <- read_excel("C:/Users/Joseph/Desktop/Grad studies MSc and Applications/AsthmaCEA2022/AsthmaCEA_Markov_2022_v6.xlsx", 
    sheet = "R-extract") %>% select(-"PSA distribution")
  t <- as_tibble(t(psa_param))
  names(t) <- t[1,]
  t<- t[-1,]
  t <- mutate_all(t, function(x) as.numeric(as.character(x)))
  rownames(t)<- c("S1", "S2")

psa_param <- apply(t,2,as.list)
rm(t)

f_gen_psa <- function(n_sim = 1000,
                      payer = "societal"){
  
  require(truncnorm)
  require(gtools)
  
### Asthma Control Probability ### (proportion: mean % of weeks with well controlled asthma)l
  p.H0_AC <- p.PRIM_AC <- rbeta(n = n_sim,
                                shape1 = psa_param[["p.H0_AC"]][["S1"]],
                                shape2 = psa_param[["p.H0_AC"]][["S2"]])
  p.SYM_AC <- rbeta(n = n_sim,
                    shape1 = psa_param[["p.SYM_AC"]][["S1"]],
                    shape2 = psa_param[["p.SYM_AC"]][["S2"]])
  
  p.H1_AC <- rbeta(n = n_sim,
                    shape1 = psa_param[["p.H1_AC"]][["S1"]],
                    shape2 = psa_param[["p.H1_AC"]][["S2"]])
  
### OTHER ###  
  #H0 entering H1
  p.H0_H1 <- 0
  
  #H1 Adherence
  pAnn.H1_H0  <- 1 - (rbeta(n = n_sim,
                    shape1 = psa_param[["p.H1_H0"]][["S1"]],
                    shape2 = psa_param[["p.H1_H0"]][["S2"]]))  # probability of non-adherence to HCP management

  p.H1_H0  <- 1 - (1-pAnn.H1_H0)^(1/52)
  
  
  #SEVR -> H1 (Recovery)
  wk.SEVR_H1 <- rexp(n_sim,1/4)      #mean of 4 weeks before exiting recovery state
  r.SEVR_H1 <- 1/wk.SEVR_H1      #weekly rate of 1 event (event being leaving SEVR state)
  p.SEVR_H1 <- 1-exp(-r.SEVR_H1)
  
  
### SEV (Severe Exacerbation) ###
  p.SCS_H0 <- p.ED_H0 <-p.Hosp_H0 <- 0 #Assumption that following severe exacerbation patient enters H1
  RR.NC <- rlnorm(n = n_sim,
                  meanlog = psa_param[["RR.NC"]][["S1"]],
                  sdlog = psa_param[["RR.NC"]][["S2"]]) #RATE ratio of exacerbation for not controlled asthma
  
  #Exacerbation proportion (SCS, ED, HOSP)
  prop.H0_SEV <- prop.PRIM_SEV <- rdirichlet(n = n_sim,
                                             c(psa_param[["prop.H0_SEV_SCS"]][["S1"]],psa_param[["prop.H0_SEV_ED"]][["S1"]],psa_param[["prop.H0_SEV_Hosp"]][["S1"]]))
  prop.SYM_SEV <- rdirichlet(n = n_sim,
                             c(psa_param[["prop.SYM_SEV_SCS2"]][["S1"]],psa_param[["prop.SYM_SEV_ED2"]][["S1"]],psa_param[["prop.SYM_SEV_Hosp2"]][["S1"]]))
  
  prop.H1_SEV <-  rdirichlet(n = n_sim,
                             c(psa_param[["prop.H1_SEV_SCS"]][["S1"]],psa_param[["prop.H1_SEV_ED"]][["S1"]],psa_param[["prop.H1_SEV_Hosp"]][["S1"]]))
  
  #Cumulative rate from SYGMA trials
  r.H0_SEVtot <- rgamma(n = n_sim,
                         shape = psa_param[["r.H0"]][["S1"]],
                         scale = psa_param[["r.H0"]][["S2"]])
                        
  r.SYM_SEVtot <- rgamma(n_sim,
                         shape = psa_param[["r.SYM_2"]][["S1"]],
                         scale = psa_param[["r.SYM_2"]][["S2"]])
  
  r.H1_SEVtot <-  rgamma(n_sim,
                         shape = psa_param[["r.H1"]][["S1"]],
                         scale = psa_param[["r.H1"]][["S2"]])
  
    #Rate of exacerbation by control group
    #controlled (C)
    r.H0C_SEV <- r.H0_SEVtot/(p.H0_AC + RR.NC - RR.NC*p.H0_AC) #yaghoubi et al.2020
    r.SYMC_SEV <- r.SYM_SEVtot/(p.SYM_AC + RR.NC - RR.NC*p.SYM_AC) #yaghoubi et al.2020
    r.H1C_SEV <- r.H1_SEVtot/(p.H1_AC + RR.NC - RR.NC*p.H1_AC) #yaghoubi et al.2020
    
    #Not controlled (NC)
    r.H0NC_SEV <- r.H0C_SEV * RR.NC
    r.SYMNC_SEV <- r.SYMC_SEV * RR.NC
    r.H1NC_SEV <- r.H1C_SEV * RR.NC

 #Rate -> transition probability
      p.H0C_SCS <- (1-exp(-r.H0C_SEV/52)) * prop.H0_SEV[,1] # weekly probability of severe exacerbation with no OTC or primatene OTC prn
      p.H0C_ED <- (1-exp(-r.H0C_SEV/52)) * prop.H0_SEV[,2]
      p.H0C_Hosp <- (1-exp(-r.H0C_SEV/52)) * prop.H0_SEV[,3]
      
      p.SYMC_SCS <- (1-exp(-r.SYMC_SEV/52)) * prop.SYM_SEV[,1]	# weekly rate of severe exacerbation with symbicort PRN
      p.SYMC_ED <- (1-exp(-r.SYMC_SEV/52)) * prop.SYM_SEV[,2]
      p.SYMC_Hosp <- (1-exp(-r.SYMC_SEV/52)) * prop.SYM_SEV[,3]
      
      p.H1C_SCS <- (1-exp(-r.H1C_SEV/52)) * prop.H1_SEV[,1]	# weekly rate of severe exacerbation with HCP management (low dose ICS + SABA)
      p.H1C_ED <- (1-exp(-r.H1C_SEV/52)) * prop.H1_SEV[,2]
      p.H1C_Hosp <- (1-exp(-r.H1C_SEV/52)) * prop.H1_SEV[,3]
      
      #Not controlled (NC)
      p.H0NC_SCS <- (1-exp(-r.H0NC_SEV/52)) * prop.H0_SEV[,1] # weekly probability of severe exacerbation with no OTC or primatene OTC prn
      p.H0NC_ED <- (1-exp(-r.H0NC_SEV/52)) * prop.H0_SEV[,2]
      p.H0NC_Hosp <- (1-exp(-r.H0NC_SEV/52)) * prop.H0_SEV[,3]
      
      p.SYMNC_SCS <- (1-exp(-r.SYMNC_SEV/52)) * prop.SYM_SEV[,1]	# weekly rate of severe exacerbation with symbicort PRN
      p.SYMNC_ED <- (1-exp(-r.SYMNC_SEV/52)) * prop.SYM_SEV[,2]
      p.SYMNC_Hosp <- (1-exp(-r.SYMNC_SEV/52)) * prop.SYM_SEV[,3]
      
      p.H1NC_SCS <- (1-exp(-r.H1NC_SEV/52)) * prop.H1_SEV[,1]	# weekly rate of severe exacerbation with HCP management (low dose ICS + SABA)
      p.H1NC_ED <- (1-exp(-r.H1NC_SEV/52)) * prop.H1_SEV[,2]
      p.H1NC_Hosp <- (1-exp(-r.H1NC_SEV/52)) * prop.H1_SEV[,3]
    
    
### Mortality parameters built in markov model ### 
OR.AF <- rlnorm(n = n_sim,
                meanlog = psa_param[["OR.AF"]][["S1"]],
                sdlog = psa_param[["OR.AF"]][["S2"]]) #OR for saba overuse

#Cost
  #Med inhalations & Drug Acquisition
  inh.PRIM <- rgamma(n_sim,
                         shape = psa_param[["inh.PRIM"]][["S1"]],
                         scale = psa_param[["inh.PRIM"]][["S2"]])

  inh.SYM <- rgamma(n_sim,
                         shape = psa_param[["inh.SYM"]][["S1"]],
                         scale = psa_param[["inh.SYM"]][["S2"]])
  
  inh.ICS <- rgamma(n_sim,
                         shape = psa_param[["inh.ICS"]][["S1"]],
                         scale = psa_param[["inh.ICS"]][["S2"]])

  inh.SABA <- rgamma(n_sim,
                         shape = psa_param[["inh.SABA"]][["S1"]],
                         scale = psa_param[["inh.SABA"]][["S2"]])
  
      c.PRIM     <- 29.78*(inh.PRIM/160) * 7               # cost of primatene
      c.SYM      <- 311.49*(inh.SYM/120) * 7            # cost of symbicort
      c.ICS      <- 326.28*(inh.ICS/120)* 7               # cost of ICS
      c.SABA     <- 54.42*(inh.SABA/200)* 7             # cost of SABA
      c.ICS_SABA <- c.ICS + c.SABA
  
  #Direct Medical Costs
  c.HCP <- (rgamma(n_sim,
                        shape = psa_param[["c.HCP"]][["S1"]],
                        scale = psa_param[["c.HCP"]][["S2"]]))/52
  c.AU <- rgamma(n_sim,
                        shape = psa_param[["c.AU"]][["S1"]],
                        scale = psa_param[["c.AU"]][["S2"]])
  
  c.SCS <- rgamma(n_sim,
                        shape = psa_param[["c.SCS"]][["S1"]],
                        scale = psa_param[["c.SCS"]][["S2"]])
  c.ED <- rgamma(n_sim,
                        shape = psa_param[["c.ED"]][["S1"]],
                        scale = psa_param[["c.ED"]][["S2"]])
  c.Hosp <- rgamma(n_sim,
                        shape = psa_param[["c.Hosp"]][["S1"]],
                        scale = psa_param[["c.Hosp"]][["S2"]])
  
  #Indirect Costs
 if(payer=="societal"){ 
   
   c.timeHCP <- (rnorm(n = n_sim,
                     mean = psa_param[["c.timeHCP"]][["S1"]],
                     sd = psa_param[["c.timeHCP"]][["S2"]] )) * (1037/(60*52.1429*35))
  
  c.prodAU <- rlnorm(n = n_sim,
                  meanlog = psa_param[["c.prodAU"]][["S1"]],
                  sdlog = psa_param[["c.prodAU"]][["S2"]]) * 1037
  
  c.prodSCS <- rlnorm(n = n_sim,
                  meanlog = psa_param[["c.prodSCS"]][["S1"]],
                  sdlog = psa_param[["c.prodSCS"]][["S2"]]) * 1037
  
  c.prodED <- rlnorm(n = n_sim,
                  meanlog = psa_param[["c.prodED"]][["S1"]],
                  sdlog = psa_param[["c.prodED"]][["S2"]]) * 1037
  
  c.prodHosp <- rlnorm(n = n_sim,
                  meanlog = psa_param[["c.prodHosp"]][["S1"]],
                  sdlog = psa_param[["c.prodHosp"]][["S2"]]) * 1037
 }
  
if(payer=="public"){ 
 
  c.timeHCP <- 0
  c.prodAU <- 0
  c.prodSCS <- 0
  c.prodED <- 0
  c.prodHosp <- 0
 }
  
  #utility
  u.H0 <- (rbeta(n = n_sim,
                  shape1 = psa_param[["u.H0"]][["S1"]],
                  shape2 = psa_param[["u.H0"]][["S2"]]))/52
  
  du.AU <- -(rlnorm(n = n_sim,
                  meanlog = psa_param[["du.AU"]][["S1"]],
                  sdlog = psa_param[["du.AU"]][["S2"]]))/52
  
  du.SCS <- -(rbeta(n = n_sim,
                  shape1 = psa_param[["du.SCS"]][["S1"]],
                  shape2 = psa_param[["du.SCS"]][["S2"]]))/52
  du.ED <- -(rbeta(n = n_sim,
                  shape1 = psa_param[["du.ED"]][["S1"]],
                  shape2 = psa_param[["du.ED"]][["S2"]]))/52
  du.Hosp <- -(rbeta(n = n_sim,
                  shape1 = psa_param[["du.Hosp"]][["S1"]],
                  shape2 = psa_param[["du.Hosp"]][["S2"]]))/52
  
  u.SCS  <- (u.H0 + du.SCS)
  u.ED   <-  (u.H0 + du.ED)
  u.Hosp <- (u.H0 + du.Hosp) 
################################################################################################################################
### Parameter dataframe ###
df_psa <- data.frame(
    ## Asthma Control Probability (proportion: mean % of weeks with well controlled asthma)l
      p.H0_AC,
      p.PRIM_AC,
      p.SYM_AC,
      p.H1_AC,
      
    ## Transition probabilities #
      #Severe Exacerbation Rates * Exacerbation Proportion
      #controlled (C)
      p.H0C_SCS, 
      p.H0C_ED,
      p.H0C_Hosp,
      
      p.SYMC_SCS,
      p.SYMC_ED,
      p.SYMC_Hosp,
      
      p.H1C_SCS,
      p.H1C_ED,
      p.H1C_Hosp,
      
      #Not controlled (NC)
      p.H0NC_SCS,
      p.H0NC_ED,
      p.H0NC_Hosp,
      
      p.SYMNC_SCS,
      p.SYMNC_ED,
      p.SYMNC_Hosp,
      
      p.H1NC_SCS,
      p.H1NC_ED,
      p.H1NC_Hosp,
    
      #SEVR -> H1
      p.SEVR_H1, #Weekly probability of exiting SEVR
    
      #H0
      p.H0_H1,
    
      #H1
      p.H1_H0,               # probability of non-adherence to HCP management
    
        
    ### Cost and utility inputs ###
      ## Direct Medical costs (per week)
      c.HCP,
      c.AU,
      c.SCS,
      c.ED,
      c.Hosp,
      
      ## Drug acquisition cost (per DAY) * 7 
      c.PRIM,
      c.SYM,
      c.ICS,
      c.SABA,
      c.ICS_SABA,
      
      ## Indirect costs 
      c.timeHCP,
      c.prodAU,
      
      #Productivity loss due to severe exacerbation ** Assuming do not go to work for 2,4,7 days
      c.prodSCS,
      c.prodED,
      c.prodHosp,
      
      ## Utility
      du.AU,
      du.SCS,
      du.ED,
      du.Hosp,
      
      
      u.H0,          # utility of non-exacerbation
      u.H1 = u.H0, 
      u.SCS,     # utility of SCS
      u.ED,
      u.Hosp,
      OR.AF
      
  )
  
  v.du_exac  <- c(du.SCS, du.ED, du.Hosp)
  v.u_exac  <- c(u.SCS, u.ED, u.Hosp)
  return(df_psa)

}
```

```{r, Markov Model, include=FALSE}
############################### Markov Model  ###########################
# The Markov function 
Markov <- function(params, v.M_1, n.t, v.n, d.c, d.e, trt=FALSE, res = TRUE) {
# Arguments:  
  # v.M_1:   initial allocation of cohort across states
  # n.t:     total number of cycles to run the model
  # v.n:     vector of health state names
  # d.c:     discount rate for costs
  # d.e:     discount rate for effectiveness (QALYs)
  # Trt:     is this the cohort receiving treatment? (default is FALSE)
  
  v.dwc <- 1 / (1 + d.c) ^ (0:n.t)   # calculate the cost discount weight based on the discount rate d.c 
  v.dwe <- 1 / (1 + d.e) ^ (0:n.t)   # calculate the QALY discount weight based on the discount rate d.e
  
  # create the transition trace matrix (m.TR) capturing the proportion of the cohort in each state at each time point
  m.TR <-  matrix(0, nrow = n.t + 1, ncol = n.s, 
                     dimnames = list( paste("cycle", 0:n.t, sep = ""), v.n))
  
  m.TR[1, ]  <- v.M_1  # indicate the initial health state
  
#Mortality: asthma fatality and baseline mortality (not affected by PSA)
  #Asthma Fatality (baseline)
    pAnn.SCS_D <- mortality$p.SCS_AF
    pAnn.ED_D <- mortality$p.ED_AF
    pAnn.Hosp_D <- mortality$p.HOSP_AF
    
    p.SCS_D <- 1 - (1-pAnn.SCS_D)^(1/52)
    p.ED_D <- 1 - (1-pAnn.ED_D)^(1/52)
    p.Hosp_D <- 1 - (1-pAnn.Hosp_D)^(1/52)
    
    #Asthma Fatality * Spitzer OR for SABA overuse
    pAnn.SCS_D_PRIM <- mortality$pSp.SCS_AF
    pAnn.ED_D_PRIM <- mortality$pSp.ED_AF
    pAnn.Hosp_D_PRIM <- mortality$pSp.HOSP_AF
    
    p.SCS_D_PRIM <- 1 - (1-pAnn.SCS_D_PRIM)^(1/52)
    p.ED_D_PRIM <- 1 - (1-pAnn.ED_D_PRIM)^(1/52)
    p.Hosp_D_PRIM <- 1 - (1-pAnn.Hosp_D_PRIM)^(1/52)
    
  #H0 Baseline Mortality
    pAnn.H0C_D <- pAnn.H0NC_D <- mortality$b_mortality   # probability of death from no HCP management
    p.H0C_D <- p.H0NC_D  <- p.H1C_D <- p.H1NC_D <-  1 - (1-pAnn.H0C_D)^(1/52)     

with(as.list(params),{  
   
  if(trt=="primatene"){
  
for (i in 2:(n.t + 1)) { 
    
  H0C.rem <- min((p.H0_H1*p.H1_AC+p.H0_H1*(1-p.H1_AC)+p.H0C_SCS+p.H0C_ED+p.H0C_Hosp+p.H0C_D[i-1]),1)
  H0NC.rem <- min((p.H0_H1*p.H1_AC+p.H0_H1*(1-p.H1_AC)+p.H0NC_SCS+p.H0NC_ED+p.H0NC_Hosp+p.H0NC_D[i-1]),1)
  H1C.rem <- min(((p.H1_H0*p.H0_AC)+(p.H1_H0*(1-p.H0_AC))+p.H1C_SCS+p.H1C_ED+p.H1C_Hosp+p.H1C_D[i-1]),1)
  H1NC.rem <- min(((p.H1_H0*p.H0_AC)+(p.H1_H0*(1-p.H0_AC))+p.H1NC_SCS+p.H1NC_ED+p.H1NC_Hosp+p.H1C_D[i-1]),1)
  
  SCS.rem <- min((p.SCS_D_PRIM[i-1]+p.H0C_D[i-1]),1)
  ED.rem <- min((p.ED_D_PRIM[i-1]+p.H0C_D[i-1]),1)
  Hosp.rem <-min((p.Hosp_D_PRIM[i-1]+p.H0C_D[i-1]),1)
  SEVR.rem <- min((p.SEVR_H1*p.H1_AC + p.SEVR_H1*(1-p.H1_AC)+p.H0C_D[i-1]),1)

    
  # create the transition matrix for each model cycle
    m.P <- matrix(c(
                    (1-H0C.rem)*p.H0_AC,(1-H0C.rem)*(1-p.H0_AC), p.H0_H1*p.H1_AC, p.H0_H1*(1-p.H1_AC), p.H0C_SCS, p.H0C_ED, p.H0C_Hosp, 0, p.H0C_D[i-1], #H0C
                    (1-H0NC.rem)*p.H0_AC,(1-H0NC.rem)*(1-p.H0_AC), p.H0_H1*p.H1_AC, p.H0_H1*(1-p.H1_AC), p.H0NC_SCS, p.H0NC_ED, p.H0NC_Hosp, 0, p.H0NC_D[i-1], #H0NC 
                    p.H1_H0*p.H0_AC,p.H1_H0*(1-p.H0_AC),(1 - H1C.rem)*p.H1_AC,(1 - H1C.rem)*(1-p.H1_AC),p.H1C_SCS,p.H1C_ED,p.H1C_Hosp, 0, p.H1C_D[i-1], #H1C
                    p.H1_H0*p.H0_AC,p.H1_H0*(1-p.H0_AC),(1 - H1NC.rem)*p.H1_AC,(1 - H1NC.rem)*(1-p.H1_AC),p.H1NC_SCS,p.H1NC_ED,p.H1NC_Hosp, 0, p.H1NC_D[i-1], #H1NC
                    0, 0, 0, 0, 0, 0, 0,(1-SCS.rem), min(p.SCS_D_PRIM[i-1]+p.H0C_D[i-1],1), #SCS
                    0, 0, 0, 0, 0, 0, 0,(1-ED.rem), min(p.ED_D_PRIM[i-1]+p.H0C_D[i-1],1), #ED
                    0, 0, 0, 0, 0, 0, 0,(1-Hosp.rem), min(p.Hosp_D_PRIM[i-1]+p.H0C_D[i-1],1), # Hosp
                    0, 0, p.SEVR_H1*p.H1_AC, p.SEVR_H1*(1-p.H1_AC), 0, 0, 0, 1-SEVR.rem, p.H0C_D[i-1], #SEVR
                    0, 0, 0, 0, 0, 0, 0, 0, 1), #D
                  nrow = n.s, ncol = n.s, byrow = T,
                  dimnames = list(v.n, v.n))
    
    # print(m.P) # show transition matrix for each model cycle to make sure p.H0_D is working - can remove after debugging
    
    # calculate the proportion of the cohort in each state at time t
    m.TR[i, ] <- t(m.TR[i - 1, ]) %*% m.P

}  # close the loop for the individuals 


  # create vectors of utility and costs for each state
  v.c <- c(
           c.PRIM, #H0C
           c.PRIM + c.AU + c.prodAU, #H0NC
           c.ICS_SABA + c.HCP + c.timeHCP, #H1C
           c.ICS_SABA + c.HCP + c.timeHCP + c.AU + c.prodAU, #H1NC
           c.SCS + c.prodSCS, #SCS
           c.ED + c.prodED, #ED
           c.Hosp + c.prodHosp, #HOSP
           c.ICS_SABA + c.HCP + c.timeHCP + c.AU + c.prodAU, #SEVR
           0) #D
  
  v.u <- c(
           u.H0, #H0C
           u.H0 + du.AU, #H0NC
           u.H1, #H1C
           u.H1 + du.AU, #H1NC
           u.SCS, #SCS
           u.ED, #ED
           u.Hosp, #HOSP
           u.H1 + du.AU,
           0) #D
  
  } 
  
  else{
  if(trt=="symbicort"){
    
  # run the simulation for symbicort
 for (i in 2:(n.t + 1)) { 
    
H0C.rem <- min((p.H0_H1*p.H1_AC+p.H0_H1*(1-p.H1_AC)+p.SYMC_SCS+p.SYMC_ED+p.SYMC_Hosp+p.H0C_D[i-1]),1)
H0NC.rem <- min((p.H0_H1*p.H1_AC+p.H0_H1*(1-p.H1_AC)+p.SYMNC_SCS+p.SYMNC_ED+p.SYMNC_Hosp+p.H0NC_D[i-1]),1)
H1C.rem <- min(((p.H1_H0*p.H0_AC)+(p.H1_H0*(1-p.H0_AC))+p.H1C_SCS+p.H1C_ED+p.H1C_Hosp+p.H1C_D[i-1]),1)
H1NC.rem <- min(((p.H1_H0*p.H0_AC)+(p.H1_H0*(1-p.H0_AC))+p.H1NC_SCS+p.H1NC_ED+p.H1NC_Hosp+p.H1C_D[i-1]),1)

SCS.rem <- min((p.SCS_D[i-1]+p.H0C_D[i-1]),1)
ED.rem <- min((p.ED_D[i-1]+p.H0C_D[i-1]),1)
Hosp.rem <- min((p.Hosp_D[i-1]+p.H0C_D[i-1]),1)
SEVR.rem <- min((p.SEVR_H1*p.H1_AC + p.SEVR_H1*(1-p.H1_AC)+p.H0C_D[i-1]),1)


  # create the transition matrix for each model cycle
    m.P <- matrix(c(
                    (1-H0C.rem)*p.SYM_AC,(1-H0C.rem)*(1-p.SYM_AC), p.H0_H1*p.H1_AC, p.H0_H1*(1-p.H1_AC), p.SYMC_SCS, p.SYMC_ED, p.SYMC_Hosp, 0, p.H0C_D[i-1], #H0C
                    (1-H0NC.rem)*p.SYM_AC,(1-H0NC.rem)*(1-p.SYM_AC), p.H0_H1*p.H1_AC, p.H0_H1*(1-p.H1_AC), p.SYMNC_SCS, p.SYMNC_ED, p.SYMNC_Hosp, 0, p.H0NC_D[i-1], #H0NC 
                    p.H1_H0*p.SYM_AC,p.H1_H0*(1-p.SYM_AC),(1 - H1C.rem)*p.H1_AC,(1 - H1C.rem)*(1-p.H1_AC),p.H1C_SCS,p.H1C_ED,p.H1C_Hosp, 0, p.H1C_D[i-1], #H1C
                    p.H1_H0*p.SYM_AC,p.H1_H0*(1-p.SYM_AC),(1 - H1NC.rem)*p.H1_AC,(1 - H1NC.rem)*(1-p.H1_AC),p.H1NC_SCS,p.H1NC_ED,p.H1NC_Hosp, 0, p.H1NC_D[i-1], #H1NC
                    0, 0, 0, 0, 0, 0, 0,(1-SCS.rem), min(p.SCS_D[i-1]+p.H0C_D[i-1],1), #SCS
                    0, 0, 0, 0, 0, 0, 0,(1-ED.rem), min(p.ED_D[i-1]+p.H0C_D[i-1],1), #ED
                    0, 0, 0, 0, 0, 0, 0,(1-Hosp.rem), min(p.Hosp_D[i-1]+p.H0C_D[i-1],1), # Hosp
                    0, 0, p.SEVR_H1*p.H1_AC, p.SEVR_H1*(1-p.H1_AC), 0, 0, 0, 1-SEVR.rem, p.H0C_D[i-1], #SEVR
                    0, 0, 0, 0, 0, 0, 0, 0, 1), #D
                  nrow = n.s, ncol = n.s, byrow = T,
                  dimnames = list(v.n, v.n))
    
    # print(m.P) # show transition matrix for each model cycle to make sure p.H0_D is working - can remove after debugging
    
    # calculate the proportion of the cohort in each state at time t
    m.TR[i, ] <- t(m.TR[i - 1, ]) %*% m.P
  
}  # close the loop for the individuals

  # create vectors of utility and costs for each state
  v.c <- c(
           c.SYM, #H0C
           c.SYM + c.AU + c.prodAU, #H0NC
           c.ICS_SABA + c.HCP + c.timeHCP, #H1C
           c.ICS_SABA + c.HCP + c.timeHCP + c.AU + c.prodAU, #H1NC
           c.SCS + c.prodSCS, #SCS
           c.ED + c.prodED, #ED
           c.Hosp + c.prodHosp, #HOSP
           c.ICS_SABA + c.HCP + c.timeHCP + c.AU + c.prodAU, #SEVR
           0) #D
  
  v.u <- c(
           u.H0, #H0C
           u.H0 + du.AU, #H0NC
           u.H1, #H1C
           u.H1 + du.AU, #H1NC
           u.SCS, #SCS
           u.ED, #ED
           u.Hosp, #HOSP
           u.H1 + du.AU, #SEVR
           0) #D
  
  }
    
  else{ #no treatment


# run the simulation for no treatment

for (i in 2:(n.t + 1)) { 
  
H0C.rem <- min((p.H0_H1*p.H1_AC+p.H0_H1*(1-p.H1_AC)+p.H0C_SCS+p.H0C_ED+p.H0C_Hosp+0+p.H0C_D[i-1]),1)
H0NC.rem <- min((p.H0_H1*p.H1_AC+p.H0_H1*(1-p.H1_AC)+p.H0NC_SCS+p.H0NC_ED+p.H0NC_Hosp+0+p.H0NC_D[i-1]),1)
H1C.rem <- min(((p.H1_H0*p.H0_AC)+(p.H1_H0*(1-p.H0_AC))+p.H1C_SCS+p.H1C_ED+p.H1C_Hosp+0+p.H1C_D[i-1]),1)
H1NC.rem <- min(((p.H1_H0*p.H0_AC)+(p.H1_H0*(1-p.H0_AC))+p.H1NC_SCS+p.H1NC_ED+p.H1NC_Hosp+0+p.H1C_D[i-1]),1)

SCS.rem <- min((p.SCS_D[i-1]+p.H0C_D[i-1]),1)
ED.rem <- min((p.ED_D[i-1]+p.H0C_D[i-1]),1)
Hosp.rem <- min((p.Hosp_D[i-1]+p.H0C_D[i-1]),1)
SEVR.rem <- min((p.SEVR_H1*p.H1_AC + p.SEVR_H1*(1-p.H1_AC)+p.H0C_D[i-1]),1)


  # create the transition matrix for each model cycle
    m.P <- matrix(c(
                    (1-H0C.rem)*p.H0_AC,(1-H0C.rem)*(1-p.H0_AC), p.H0_H1*p.H1_AC, p.H0_H1*(1-p.H1_AC), p.H0C_SCS, p.H0C_ED, p.H0C_Hosp, 0, p.H0C_D[i-1], #H0C
                    (1-H0NC.rem)*p.H0_AC,(1-H0NC.rem)*(1-p.H0_AC), p.H0_H1*p.H1_AC, p.H0_H1*(1-p.H1_AC), p.H0NC_SCS, p.H0NC_ED, p.H0NC_Hosp,0, p.H0NC_D[i-1], #H0NC 
                    p.H1_H0*p.H0_AC,p.H1_H0*(1-p.H0_AC),(1 - H1C.rem)*p.H1_AC,(1 - H1C.rem)*(1-p.H1_AC),p.H1C_SCS,p.H1C_ED,p.H1C_Hosp,0, p.H1C_D[i-1], #H1C
                    p.H1_H0*p.H0_AC,p.H1_H0*(1-p.H0_AC),(1 - H1NC.rem)*p.H1_AC,(1 - H1NC.rem)*(1-p.H1_AC),p.H1NC_SCS,p.H1NC_ED,p.H1NC_Hosp,0, p.H1NC_D[i-1], #H1NC
                    0, 0, 0, 0, 0, 0, 0,(1-SCS.rem), min(p.SCS_D[i-1]+p.H0C_D[i-1],1), #SCS
                    0, 0, 0, 0, 0, 0, 0,(1-ED.rem), min(p.ED_D[i-1]+p.H0C_D[i-1],1), #ED
                    0, 0, 0, 0, 0, 0, 0,(1-Hosp.rem), min(p.Hosp_D[i-1]+p.H0C_D[i-1],1), # Hosp
                    0, 0, p.SEVR_H1*p.H1_AC, p.SEVR_H1*(1-p.H1_AC), 0, 0, 0, 1-SEVR.rem, p.H0C_D[i-1], #SEVR
                    0, 0, 0, 0, 0, 0, 0, 0, 1), #D
                  nrow = n.s, ncol = n.s, byrow = T,
                  dimnames = list(v.n, v.n))
    
    # print(i-1)
    # print(p.H0C_D[i-1])
    m.TR[i, ] <- t(m.TR[i - 1, ]) %*% m.P
    # calculate the proportion of the cohort in each state at time t
  } # close the loop for the individuals 


  # create vectors of utility and costs for each state
  v.c <- c(
           0, #H0C
           c.AU + c.prodAU, #H0NC
           c.ICS_SABA + c.HCP + c.timeHCP, #H1C
           c.ICS_SABA + c.HCP + c.timeHCP + c.AU + c.prodAU, #H1NC
           c.SCS + c.prodSCS, #SCS
           c.ED + c.prodED, #ED
           c.Hosp + c.prodHosp, #HOSP
           c.ICS_SABA + c.HCP + c.timeHCP + c.AU + c.prodAU, #SEVR
           0) #D
  
  v.u <- c(
           u.H0, #H0C
           u.H0 + du.AU, #H0NC
           u.H1, #H1C
           u.H1 + du.AU, #H1NC
           u.SCS, #SCS
           u.ED, #ED
           u.Hosp, #HOSP
           u.H1 + du.AU, #SEVR
           0) #D
  

}
 
}

tc <-( m.TR %*% v.c)  # calculate the costs
te <-( m.TR %*% v.u ) # calculate the QALYs


tc_hat <- t(tc) %*% v.dwc  # total (discounted) cost 
te_hat <- t(te) %*% v.dwe  # total (discounted) QALY 

#outcomes
  m.TR_temp <- as_tibble(m.TR)
  
  cont <- sum(m.TR_temp$H0C + m.TR_temp$H1C)*7
  UC <- sum(m.TR_temp$H0NC + m.TR_temp$H1NC + m.TR_temp$SEVR)*7
  
  SCSoutcome <- sum(m.TR_temp$SCS)
  EDoutcome <- sum(m.TR_temp$ED)
  Hospoutcome <- sum(m.TR_temp$HOSP)
  
  SEVoutcome <- sum(m.TR_temp$SCS + m.TR_temp$ED + m.TR_temp$HOSP)

  if(res==TRUE){

results <- list(m.TR = m.TR, tc_hat = tc_hat, te_hat = te_hat, tc=tc, te=te, v.dwc=v.dwc, v.dwe=v.dwe, vc=v.c,
                controlled = cont, uncontrolled = UC, severe_exac = SEVoutcome) # store the results from the simulation in a list 


return(results)  # return the results
  } else{
    
     results <- c(
      "Cost" = tc_hat, 
      "QALY"   = te_hat, 
      "Control" = cont, 
      "Exac" = SEVoutcome
    )
    

return(results)  # return the results
  }
    
  
}) # end with function
}

```

```{r, Wrapper Function, include = F}
### Wrapper <- probablistic function
  f_wrapper <- function(fxn=f_gen_base(),
                        n_sim = 1000,
                        n.t = 52*77,
                        d.c = (0.03/52),
                        trt=FALSE){
    
    require(readr)
    require(tidyverse)

  ### Non-adjustable model inputs
    n.t   <- n.t             # time horizon, lifetime from 23yrs, 1 week cycle
    
    v.n   <- c("H0C","H0NC", #H0 no hcp mgt
               "H1C", "H1NC", #H1 HCP MGT
               "SCS","ED","HOSP", "SEVR", #SEV exacerbation
               "D") #death
    
    n.s   <- length(v.n)                 # the number of health states
    v.M_1 <- c(1,0,0,0,0,0,0,0,0)          # Initial health state distribution - Everyone starts at controlled no HCP management
    
    d.c   <- d.e <- d.c           # equal discounting of costs and QALYs by 3% per year
    v.Trt <- c("No OTC", 
               "Primatene", 
               "Symbicort")       # store the strategy names
  

  ### Reading in enviroment 
    environment(fxn) <- environment()
    environment(Markov)   <- environment()
    
#PSA parameters
    df_psa <- fxn
    
    #--  Run PSA  --#
    
    # Initialize matrix of results outcomes
    m_out <- matrix(NaN, 
                    nrow = n_sim, 
                    ncol = 4,
                    dimnames = list(1:n_sim,
                                    c("Costs", "QALYs",
                                      "Control", "Exac")))
    
    # run model for each row of PSA inputs
    for(t in 1:n_sim){
      mortality <- mort.list[[t]]
      
      # store results in row of results matrix
      m_out[t,] <- Markov(df_psa[t,], v.M_1, n.t, v.n, d.c, d.e, trt = trt, res=FALSE) 
    } # close model loop
    
    
    #-- Return results --#
    
    # convert matrix to dataframe (for plots)
    df_out <- as.data.frame(m_out) 
    
    # output the dataframe from the function  
    return(df_out) 
    
  } # end of function
```

```{r, summary_markov, include = F}
summary_markov <- function(df, wtp=100000){
  table_markov <- df %>% group_by(trt) %>% summarise(Costs = mean(Costs),
                                                      QALYs = mean(QALYs),
                                                      Control = mean(Control),
                                                      Exac = mean(Exac)
                                                      ) %>% mutate(delta_Costs = c(Costs[1]-Costs[2], NA, Costs[3]-Costs[2]),
                                                                   delta_QALYs = c(QALYs[1]-QALYs[2], NA, QALYs[3]-QALYs[2]), 
                                                                   delta_Control = c(Control[1]-Control[2], NA, Control[3]-Control[2]),
                                                                   delta_Exac = c(Exac[1]-Exac[2], NA, Exac[3]-Exac[2]),
                                                                   ICER=delta_Costs/delta_QALYs,
                                                                   INMB=delta_QALYs*wtp - delta_Costs
                                                                   )
}
```

```{r, CEA_plot, include = FALSE}
    CEA_plot <- function(data, 
                         x, y, 
                         title=NULL,
                         xlab=NULL, ylab=NULL){
      p <- ggplot(data = data,
             aes(x,y))+
        geom_point()+
        stat_ellipse()+
        labs(x=xlab, y=ylab, title=title)+
        geom_hline(yintercept = 0)+
        geom_vline(xintercept = 0)+
        theme_bw() + theme(panel.border = element_blank(),
                           # panel.grid.major = element_blank(),
                           # panel.grid.minor = element_blank(), 
                           axis.line = element_line(colour = "black") 
                            )
        
    return(p)
    }
```


# Analysis
```{r, Base Case, include = F}
m <- read_csv("mortality.csv")
mort.list <- list(m)

### Cost-effectiveness analysis - Default wrapper function is basecase
sim_base_no_trt  <- f_wrapper(n_sim=1) 
sim_base_PRIM    <- f_wrapper(n_sim=1, trt = "primatene") 
sim_base_SYMB    <- f_wrapper(n_sim=1, trt="symbicort")  


# create the cost-effectiveness table
base <- rbind(sim_base_no_trt, sim_base_PRIM, sim_base_SYMB)
base$trt <- c("noTrt","PRIM","SYMB")

base_table_markov <- summary_markov(base)
```

```{r, DSA, include = F}
dsa <- read_csv("C:\\Users\\Joseph\\Desktop\\Grad studies MSc and Applications\\AsthmaCEA2022\\Preliminary results\\DSAResults.csv") 


#results_wide
dsaw <- pivot_wider(dsa, names_from = trt, 
                    values_from = c(Costs, QALYs, Control, Exac))


SP <- dsaw %>% select(parameter, level, Costs_PRIM, Costs_SYMB, QALYs_PRIM, QALYs_SYMB)
  SP$delta_Costs <- SP$Costs_SYMB - SP$Costs_PRIM
  SP$delta_QALYs <- SP$QALYs_SYMB - SP$QALYs_PRIM

NP <- dsaw %>% select(parameter, level, Costs_PRIM, Costs_noTrt, QALYs_PRIM, QALYs_noTrt)
  NP$delta_Costs <- NP$Costs_noTrt - NP$Costs_PRIM
  NP$delta_QALYs <- NP$QALYs_noTrt - NP$QALYs_PRIM



tornado_plot <- function(df, wtp=100000){
  
  #calculating INMB
  df <- df %>% select(parameter,level,delta_Costs,delta_QALYs)
  df$INMB <- df$delta_QALYs * wtp - df$delta_Costs 
  
  #renaming columns & setting order for differences
  df <- df %>% select(parameter, level, INMB) %>%  pivot_wider(names_from = level, values_from = INMB) %>% rename(Parameter=parameter,
                                                                                                                      Lower_Bound = low,
                                                                                                                      Upper_Bound = high)
  df$UL_Difference <- abs(df$Upper_Bound - df$Lower_Bound)
  base.value <- df$Lower_Bound[1] #basecase value: when H0 to H1 is 0
  
  dsa_names<-c("Annual probability - Transitioning from no HCP to HCP (0%,20%)","Annual probability - Non-adherence to HCP (+/-20%) ",
             "Annual rate of severe exacerbation - no treatment/inhaled epinephrine (+/-20%)","Annual rate of severe exacerbation - bud-form (+/-20%)", "Annual rate of severe exacerbation - HCP (+/-20%)",
             "Cost - HCP management (+/-20%)","Cost - Asthma Uncontrolled Day (+/-20%)","Cost of severe exacerbation - SCS use (+/-20%) ","Cost of severe exacerbation - ED visit + SCS use (+/-20%)","Cost of severe exacerbation - Hospitalization (+/-20%)",
             "Inhalations per day - inhaled epinephrine (+/-20%)","Inhalations per day - bud-form (+/-20%)","Inhalations per day - ICS (+/-20%)","Inhalations per day - inhaled SABA (+/-20%)",
             "Disutility - Asthma Uncontrolled Day (+/-20%)","Disutility of severe exacerbation - SCS use (+/-20%)","Disutility of severe exacerbation - ED visit + SCS use (+/-20%)","Disutility of severe exacerbation - Hospitalization (+/-20%)","Utility - non-exacerbation (+/-20%)")
  
  df$Parameter <- dsa_names
  # get order of parameters according to size of intervals
  order.parameters <- df %>% arrange(UL_Difference) %>%
    mutate(Parameter=factor(x=Parameter, levels=Parameter)) %>%
    select(Parameter) %>% unlist() %>% levels()
  
  # width of columns in plot (value between 0 and 1)
  width <- 0.95
  
  # get data frame in shape for ggplot and geom_rect
  df.2 <- df %>% 
    # gather columns Lower_Bound and Upper_Bound into a single column using gather
    gather(key='type', value='output.value', Lower_Bound:Upper_Bound) %>%
    # just reordering columns
    select(Parameter, type, output.value, UL_Difference) %>%
    # create the columns for geom_rect
    mutate(Parameter=factor(Parameter, levels=order.parameters),
           ymin=pmin(output.value, base.value),
           ymax=pmax(output.value, base.value),
           xmin=as.numeric(Parameter)-width/2,
           xmax=as.numeric(Parameter)+width/2)
  
p <- ggplot() + 
    geom_rect(data = df.2, 
              aes(ymax=ymax, ymin=ymin, xmax=xmax, xmin=xmin, fill=type)) +
    theme_bw() + 
    theme(axis.title.y=element_blank(), legend.position = 'bottom',
          legend.title = element_blank()) + 
    geom_hline(yintercept = base.value) +
    scale_x_continuous(breaks = c(1:length(order.parameters)), 
                       labels = order.parameters) +
    labs(xlab="INMB")+
    coord_flip()
  
list(df,p)
}
```

```{r, PSA, include = F}
psa <- read_csv("C:\\Users\\Joseph\\Desktop\\Grad studies MSc and Applications\\AsthmaCEA2022\\Preliminary results\\PSAResults_ALLv4.csv")
psa$ID <- rep(1:1000,3)
psa_table_markov <- summary_markov(psa)

#results_wide
resw <- pivot_wider(psa, names_from = trt, 
                        values_from = c(Costs, QALYs, Control, Exac))
  
  #Delta SYMB vs PRIM
  resw$deltaSP_Costs <- resw$Costs_SYMB - resw$Costs_PRIM
  resw$deltaSP_QALYs <- resw$QALYs_SYMB - resw$QALYs_PRIM
  
  #Delta noTrt vs PRIM
  resw$deltaNP_Costs <- resw$Costs_noTrt - resw$Costs_PRIM
  resw$deltaNP_QALYs <- resw$QALYs_noTrt - resw$QALYs_PRIM


```

```{r, scenario, include = F}
res_dc0 <- read_csv("C:\\Users\\Joseph\\Desktop\\Grad studies MSc and Applications\\AsthmaCEA2022\\Preliminary results\\scenario_dc0.csv")
res_dc6 <- read_csv("C:\\Users\\Joseph\\Desktop\\Grad studies MSc and Applications\\AsthmaCEA2022\\Preliminary results\\scenario_dc6.csv")
res_th10 <- read_csv("C:\\Users\\Joseph\\Desktop\\Grad studies MSc and Applications\\AsthmaCEA2022\\Preliminary results\\scenario_th10.csv")
res_th30 <- read_csv("C:\\Users\\Joseph\\Desktop\\Grad studies MSc and Applications\\AsthmaCEA2022\\Preliminary results\\scenario_th30.csv")
res_public <- read_csv("C:\\Users\\Joseph\\Desktop\\Grad studies MSc and Applications\\AsthmaCEA2022\\Preliminary results\\scenario_public.csv")

scen <- list(dc0=res_dc0,dc6=res_dc6,th10=res_th10,th30=res_th30,public=res_public) #creating list of scenario results
ID <- function(df){
  ID <- rep(1:1000,3)

  df <- cbind(df,ID)
} #unique ID for PSA 1 -> 1000 fpr comparison

scen <- lapply(scen,ID) 

scen_table_markov <- lapply(scen,summary_markov)
scen_table_markov_spread <- bind_rows(scen_table_markov) #spreading data into spread sheet to examine on csv
names<-c("dc0","dc6","th10", "th30", "public") %>% rep(each=3) # applying names results
  scen_table_markov_spread$ID <- names
```

# Tables

## Base case
```{r, Base case table}
base_table_markov 
```
```{r, psa table}
psa_table_markov
```

```{r, scenario table}
scen_table_markov_spread
```


# Figures

##Tornado
```{r, Tornado plot}
tornado_plot(SP)
tornado_plot(NP)

```

##CEA plot
```{r, CEA plot}
CEA_plot(data = resw, x = resw$deltaSP_QALYs, y = resw$deltaSP_Costs, title = "SYMB")

CEA_plot(data = resw, x = resw$deltaNP_QALYs, y = resw$deltaNP_Costs, title = "noTrt")
```

